-- SUPABASE DATABASE SETUP SCRIPT
-- Run this in Supabase SQL Editor to create the required tables

-- =====================================================
-- STEP 1: Create the tables
-- =====================================================

-- Firms table (DISCOM utilities)
CREATE TABLE IF NOT EXISTS firms (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    address TEXT,
    contact_no TEXT,
    gst_no TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Client Firms table (User's own companies)
CREATE TABLE IF NOT EXISTS client_firms (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firm_name TEXT NOT NULL UNIQUE,
    address TEXT,
    contact_no TEXT,
    gst_no TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tenders table
CREATE TABLE IF NOT EXISTS tenders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firm_id BIGINT REFERENCES firms(id) ON DELETE CASCADE,
    tn_number TEXT NOT NULL,
    po_number TEXT,
    work_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(firm_id, tn_number)
);

-- Bills table
CREATE TABLE IF NOT EXISTS bills (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tender_id BIGINT REFERENCES tenders(id) ON DELETE SET NULL,
    firm_id BIGINT REFERENCES firms(id) ON DELETE CASCADE,
    supplier_firm_id BIGINT REFERENCES firms(id) ON DELETE SET NULL,
    client_firm_id BIGINT REFERENCES client_firms(id) ON DELETE SET NULL,
    tn_number TEXT NOT NULL,
    bill_date TIMESTAMPTZ NOT NULL,
    due_date TIMESTAMPTZ NOT NULL,
    amount DECIMAL(15,2) DEFAULT 0,
    invoice_amount DECIMAL(15,2) DEFAULT 0,
    csd_amount DECIMAL(15,2) DEFAULT 0,
    bill_pass_amount DECIMAL(15,2) DEFAULT 0,
    csd_released_date TIMESTAMPTZ,
    scrap_amount DECIMAL(15,2) DEFAULT 0,
    scrap_gst_amount DECIMAL(15,2) DEFAULT 0,
    md_ld_amount DECIMAL(15,2) DEFAULT 0,
    empty_oil_issued DECIMAL(15,2) DEFAULT 0,
    empty_oil_returned DECIMAL(15,2) DEFAULT 0,
    tds_amount DECIMAL(15,2) DEFAULT 0,
    tcs_amount DECIMAL(15,2) DEFAULT 0,
    gst_tds_amount DECIMAL(15,2) DEFAULT 0,
    total_paid DECIMAL(15,2) DEFAULT 0,
    due_amount DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    paid_date TIMESTAMPTZ,
    transaction_no TEXT,
    due_release_date TIMESTAMPTZ,
    invoice_no TEXT,
    invoice_date TIMESTAMPTZ,
    work_order_no TEXT,
    work_order_date TIMESTAMPTZ,
    consignment_name TEXT,
    invoice_type TEXT,
    proof_path TEXT,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Payments table
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bill_id BIGINT REFERENCES bills(id) ON DELETE CASCADE,
    payment_date TIMESTAMPTZ NOT NULL,
    amount_paid DECIMAL(15,2) DEFAULT 0,
    paid_date TIMESTAMPTZ,
    transaction_no TEXT,
    due_release_date TIMESTAMPTZ,
    invoice_no TEXT,
    invoice_date TIMESTAMPTZ,
    work_order_no TEXT,
    work_order_date TIMESTAMPTZ,
    consignment_name TEXT,
    proof_path TEXT,
    remarks TEXT,
    last_edited TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- STEP 2: Create indexes for performance
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_tenders_firm ON tenders(firm_id);
CREATE INDEX IF NOT EXISTS idx_bills_firm ON bills(firm_id);
CREATE INDEX IF NOT EXISTS idx_bills_tender ON bills(tender_id);
CREATE INDEX IF NOT EXISTS idx_bills_status ON bills(status);
CREATE INDEX IF NOT EXISTS idx_bills_due_date ON bills(due_date);
CREATE INDEX IF NOT EXISTS idx_payments_bill ON payments(bill_id);

-- =====================================================
-- STEP 3: Enable Row Level Security (RLS)
-- =====================================================

ALTER TABLE firms ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_firms ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenders ENABLE ROW LEVEL SECURITY;
ALTER TABLE bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- STEP 4: Create policies for anonymous access
-- (For a simple setup - all users can read/write)
-- =====================================================

-- Allow all operations for anonymous users (using anon key)
CREATE POLICY "Allow all for anon" ON firms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON client_firms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON tenders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON bills FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON payments FOR ALL USING (true) WITH CHECK (true);

-- =====================================================
-- STEP 5: Create updated_at trigger function
-- =====================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to all tables
CREATE TRIGGER update_firms_updated_at
    BEFORE UPDATE ON firms
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_client_firms_updated_at
    BEFORE UPDATE ON client_firms
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tenders_updated_at
    BEFORE UPDATE ON tenders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_bills_updated_at
    BEFORE UPDATE ON bills
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- STEP 6: Enable Realtime for live sync
-- =====================================================

-- Go to Database > Replication in Supabase dashboard
-- Enable replication for: firms, client_firms, tenders, bills, payments

-- Or run this (requires superuser):
-- ALTER PUBLICATION supabase_realtime ADD TABLE firms;
-- ALTER PUBLICATION supabase_realtime ADD TABLE client_firms;
-- ALTER PUBLICATION supabase_realtime ADD TABLE tenders;
-- ALTER PUBLICATION supabase_realtime ADD TABLE bills;
-- ALTER PUBLICATION supabase_realtime ADD TABLE payments;

-- =====================================================
-- DONE! Your Supabase database is ready.
-- =====================================================

-- Default DISCOM Firms (optional - matches local defaults)
INSERT INTO firms (name, code, description) VALUES 
    ('AVVNL', 'AVVNL', 'Ajmer Vidyut Vitran Nigam Limited'),
    ('JVVNL', 'JVVNL', 'Jaipur Vidyut Vitran Nigam Limited'),
    ('JDVVNL', 'JDVVNL', 'Jodhpur Vidyut Vitran Nigam Limited')
ON CONFLICT (name) DO NOTHING;
